# Generated by Django 6.0.1 on 2026-01-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='validity',
        ),
        migrations.AddField(
            model_name='offer',
            name='validity_days',
            field=models.IntegerField(default=30, help_text='Validity in days'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('internet', 'Internet'), ('fibre', 'Fibre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
